# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0016_auto_20181003_0903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailBlacklist',
        ),
    ]
